version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://shane:s0crat3s@localhost/zipnews
      - RUST_LOG=info
    depends_on:
      - nats
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"

#  db:
#    image: postgres:15
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=postgres
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#volumes:
#  pgdata:

